// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
  numberOfOrders:          number;
  paidOrders:              number;
  numberOfClients:         number;
  numberOfProducts:        number;
  lowInventory:            number;
  productswithNoInventory: number;
  notPaidOrders:           number;
}
